version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HASHED_PASSWORD=$$2b$$12$$JeVDoAHO57Xu2dT9grzcAejh4y0UAa4ACdub.Fxi5ySRez85GY/Ha
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./backend/temp:/app/backend/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service pour les tâches automatisées (optionnel)
  scheduler:
    build: .
    command: ["node", "backend/services/scheduler.js"]
    environment:
      - NODE_ENV=production
      - HASHED_PASSWORD=$$2b$$12$$JeVDoAHO57Xu2dT9grzcAejh4y0UAa4ACdub.Fxi5ySRez85GY/Ha
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
    restart: unless-stopped
    depends_on:
      - app 